/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * PexCoin Trading Platform API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AdminAuthResponse,
  AdminLoginBody,
  AdminStats,
  AdminTransaction,
  AdminUpdateUserBody,
  AdminUser,
  AuthResponse,
  CheckoutResponse,
  CoinChartPoint,
  CreateCheckoutBody,
  CreateOpenaiConversationBody,
  CreateTransactionBody,
  CryptoPrice,
  ErrorResponse,
  GetCoinChartParams,
  HealthStatus,
  LoginBody,
  MessageResponse,
  OpenaiConversation,
  OpenaiConversationWithMessages,
  OpenaiError,
  OpenaiMessage,
  RegisterBody,
  SendOpenaiMessageBody,
  StripeProductsResponse,
  TickerItem,
  Transaction,
  User,
  UserBalance,
} from "./api.schemas";

import { customFetch } from "./custom-fetch";
import type { ErrorType, BodyType } from "./custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns server health status
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Register a new user
 */
export const getRegisterUrl = () => {
  return `/api/auth/register`;
};

export const register = async (
  registerBody: RegisterBody,
  options?: RequestInit,
): Promise<AuthResponse> => {
  return customFetch<AuthResponse>(getRegisterUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(registerBody),
  });
};

export const getRegisterMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof register>>,
    TError,
    { data: BodyType<RegisterBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof register>>,
  TError,
  { data: BodyType<RegisterBody> },
  TContext
> => {
  const mutationKey = ["register"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof register>>,
    { data: BodyType<RegisterBody> }
  > = (props) => {
    const { data } = props ?? {};

    return register(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof register>>
>;
export type RegisterMutationBody = BodyType<RegisterBody>;
export type RegisterMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Register a new user
 */
export const useRegister = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof register>>,
    TError,
    { data: BodyType<RegisterBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof register>>,
  TError,
  { data: BodyType<RegisterBody> },
  TContext
> => {
  return useMutation(getRegisterMutationOptions(options));
};

/**
 * @summary Login user
 */
export const getLoginUrl = () => {
  return `/api/auth/login`;
};

export const login = async (
  loginBody: LoginBody,
  options?: RequestInit,
): Promise<AuthResponse> => {
  return customFetch<AuthResponse>(getLoginUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(loginBody),
  });
};

export const getLoginMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    { data: BodyType<LoginBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: BodyType<LoginBody> },
  TContext
> => {
  const mutationKey = ["login"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof login>>,
    { data: BodyType<LoginBody> }
  > = (props) => {
    const { data } = props ?? {};

    return login(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof login>>
>;
export type LoginMutationBody = BodyType<LoginBody>;
export type LoginMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Login user
 */
export const useLogin = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    { data: BodyType<LoginBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: BodyType<LoginBody> },
  TContext
> => {
  return useMutation(getLoginMutationOptions(options));
};

/**
 * @summary Logout user
 */
export const getLogoutUrl = () => {
  return `/api/auth/logout`;
};

export const logout = async (
  options?: RequestInit,
): Promise<MessageResponse> => {
  return customFetch<MessageResponse>(getLogoutUrl(), {
    ...options,
    method: "POST",
  });
};

export const getLogoutMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logout>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof logout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["logout"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof logout>>,
    void
  > = () => {
    return logout(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof logout>>
>;

export type LogoutMutationError = ErrorType<unknown>;

/**
 * @summary Logout user
 */
export const useLogout = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logout>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof logout>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getLogoutMutationOptions(options));
};

/**
 * @summary Get current user
 */
export const getGetMeUrl = () => {
  return `/api/auth/me`;
};

export const getMe = async (options?: RequestInit): Promise<User> => {
  return customFetch<User>(getGetMeUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMeQueryKey = () => {
  return [`/api/auth/me`] as const;
};

export const getGetMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({
    signal,
  }) => getMe({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMe>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>;
export type GetMeQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get current user
 */

export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMeQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get all crypto pair prices
 */
export const getGetCryptoPricesUrl = () => {
  return `/api/crypto/prices`;
};

export const getCryptoPrices = async (
  options?: RequestInit,
): Promise<CryptoPrice[]> => {
  return customFetch<CryptoPrice[]>(getGetCryptoPricesUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetCryptoPricesQueryKey = () => {
  return [`/api/crypto/prices`] as const;
};

export const getGetCryptoPricesQueryOptions = <
  TData = Awaited<ReturnType<typeof getCryptoPrices>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getCryptoPrices>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCryptoPricesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCryptoPrices>>> = ({
    signal,
  }) => getCryptoPrices({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCryptoPrices>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCryptoPricesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCryptoPrices>>
>;
export type GetCryptoPricesQueryError = ErrorType<unknown>;

/**
 * @summary Get all crypto pair prices
 */

export function useGetCryptoPrices<
  TData = Awaited<ReturnType<typeof getCryptoPrices>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getCryptoPrices>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetCryptoPricesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get historical chart data for a coin from CoinGecko
 */
export const getGetCoinChartUrl = (
  coinId: string,
  params?: GetCoinChartParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/crypto/chart/${coinId}?${stringifiedParams}`
    : `/api/crypto/chart/${coinId}`;
};

export const getCoinChart = async (
  coinId: string,
  params?: GetCoinChartParams,
  options?: RequestInit,
): Promise<CoinChartPoint[]> => {
  return customFetch<CoinChartPoint[]>(getGetCoinChartUrl(coinId, params), {
    ...options,
    method: "GET",
  });
};

export const getGetCoinChartQueryKey = (
  coinId: string,
  params?: GetCoinChartParams,
) => {
  return [`/api/crypto/chart/${coinId}`, ...(params ? [params] : [])] as const;
};

export const getGetCoinChartQueryOptions = <
  TData = Awaited<ReturnType<typeof getCoinChart>>,
  TError = ErrorType<unknown>,
>(
  coinId: string,
  params?: GetCoinChartParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getCoinChart>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCoinChartQueryKey(coinId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCoinChart>>> = ({
    signal,
  }) => getCoinChart(coinId, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!coinId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCoinChart>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCoinChartQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCoinChart>>
>;
export type GetCoinChartQueryError = ErrorType<unknown>;

/**
 * @summary Get historical chart data for a coin from CoinGecko
 */

export function useGetCoinChart<
  TData = Awaited<ReturnType<typeof getCoinChart>>,
  TError = ErrorType<unknown>,
>(
  coinId: string,
  params?: GetCoinChartParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getCoinChart>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetCoinChartQueryOptions(coinId, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get top market ticker data (BTC, ETH, BCH)
 */
export const getGetMarketTickerUrl = () => {
  return `/api/crypto/ticker`;
};

export const getMarketTicker = async (
  options?: RequestInit,
): Promise<TickerItem[]> => {
  return customFetch<TickerItem[]>(getGetMarketTickerUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMarketTickerQueryKey = () => {
  return [`/api/crypto/ticker`] as const;
};

export const getGetMarketTickerQueryOptions = <
  TData = Awaited<ReturnType<typeof getMarketTicker>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMarketTicker>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMarketTickerQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMarketTicker>>> = ({
    signal,
  }) => getMarketTicker({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMarketTicker>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMarketTickerQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMarketTicker>>
>;
export type GetMarketTickerQueryError = ErrorType<unknown>;

/**
 * @summary Get top market ticker data (BTC, ETH, BCH)
 */

export function useGetMarketTicker<
  TData = Awaited<ReturnType<typeof getMarketTicker>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMarketTicker>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMarketTickerQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get current user transactions
 */
export const getGetMyTransactionsUrl = () => {
  return `/api/transactions`;
};

export const getMyTransactions = async (
  options?: RequestInit,
): Promise<Transaction[]> => {
  return customFetch<Transaction[]>(getGetMyTransactionsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMyTransactionsQueryKey = () => {
  return [`/api/transactions`] as const;
};

export const getGetMyTransactionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyTransactions>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMyTransactions>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyTransactionsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMyTransactions>>
  > = ({ signal }) => getMyTransactions({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyTransactions>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMyTransactionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyTransactions>>
>;
export type GetMyTransactionsQueryError = ErrorType<unknown>;

/**
 * @summary Get current user transactions
 */

export function useGetMyTransactions<
  TData = Awaited<ReturnType<typeof getMyTransactions>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMyTransactions>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMyTransactionsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a deposit or withdrawal request
 */
export const getCreateTransactionUrl = () => {
  return `/api/transactions`;
};

export const createTransaction = async (
  createTransactionBody: CreateTransactionBody,
  options?: RequestInit,
): Promise<Transaction> => {
  return customFetch<Transaction>(getCreateTransactionUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createTransactionBody),
  });
};

export const getCreateTransactionMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTransaction>>,
    TError,
    { data: BodyType<CreateTransactionBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createTransaction>>,
  TError,
  { data: BodyType<CreateTransactionBody> },
  TContext
> => {
  const mutationKey = ["createTransaction"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createTransaction>>,
    { data: BodyType<CreateTransactionBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createTransaction(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateTransactionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createTransaction>>
>;
export type CreateTransactionMutationBody = BodyType<CreateTransactionBody>;
export type CreateTransactionMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Create a deposit or withdrawal request
 */
export const useCreateTransaction = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTransaction>>,
    TError,
    { data: BodyType<CreateTransactionBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createTransaction>>,
  TError,
  { data: BodyType<CreateTransactionBody> },
  TContext
> => {
  return useMutation(getCreateTransactionMutationOptions(options));
};

/**
 * @summary Get current user balance
 */
export const getGetMyBalanceUrl = () => {
  return `/api/users/balance`;
};

export const getMyBalance = async (
  options?: RequestInit,
): Promise<UserBalance> => {
  return customFetch<UserBalance>(getGetMyBalanceUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMyBalanceQueryKey = () => {
  return [`/api/users/balance`] as const;
};

export const getGetMyBalanceQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyBalance>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMyBalance>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyBalanceQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyBalance>>> = ({
    signal,
  }) => getMyBalance({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyBalance>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMyBalanceQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyBalance>>
>;
export type GetMyBalanceQueryError = ErrorType<unknown>;

/**
 * @summary Get current user balance
 */

export function useGetMyBalance<
  TData = Awaited<ReturnType<typeof getMyBalance>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMyBalance>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMyBalanceQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Admin login
 */
export const getAdminLoginUrl = () => {
  return `/api/admin/login`;
};

export const adminLogin = async (
  adminLoginBody: AdminLoginBody,
  options?: RequestInit,
): Promise<AdminAuthResponse> => {
  return customFetch<AdminAuthResponse>(getAdminLoginUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(adminLoginBody),
  });
};

export const getAdminLoginMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminLogin>>,
    TError,
    { data: BodyType<AdminLoginBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminLogin>>,
  TError,
  { data: BodyType<AdminLoginBody> },
  TContext
> => {
  const mutationKey = ["adminLogin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminLogin>>,
    { data: BodyType<AdminLoginBody> }
  > = (props) => {
    const { data } = props ?? {};

    return adminLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminLogin>>
>;
export type AdminLoginMutationBody = BodyType<AdminLoginBody>;
export type AdminLoginMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Admin login
 */
export const useAdminLogin = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminLogin>>,
    TError,
    { data: BodyType<AdminLoginBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof adminLogin>>,
  TError,
  { data: BodyType<AdminLoginBody> },
  TContext
> => {
  return useMutation(getAdminLoginMutationOptions(options));
};

/**
 * @summary Admin get all users
 */
export const getAdminGetUsersUrl = () => {
  return `/api/admin/users`;
};

export const adminGetUsers = async (
  options?: RequestInit,
): Promise<AdminUser[]> => {
  return customFetch<AdminUser[]>(getAdminGetUsersUrl(), {
    ...options,
    method: "GET",
  });
};

export const getAdminGetUsersQueryKey = () => {
  return [`/api/admin/users`] as const;
};

export const getAdminGetUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof adminGetUsers>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof adminGetUsers>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdminGetUsersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetUsers>>> = ({
    signal,
  }) => adminGetUsers({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminGetUsers>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AdminGetUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminGetUsers>>
>;
export type AdminGetUsersQueryError = ErrorType<unknown>;

/**
 * @summary Admin get all users
 */

export function useAdminGetUsers<
  TData = Awaited<ReturnType<typeof adminGetUsers>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof adminGetUsers>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAdminGetUsersQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Admin get user by ID
 */
export const getAdminGetUserUrl = (id: string) => {
  return `/api/admin/users/${id}`;
};

export const adminGetUser = async (
  id: string,
  options?: RequestInit,
): Promise<AdminUser> => {
  return customFetch<AdminUser>(getAdminGetUserUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getAdminGetUserQueryKey = (id: string) => {
  return [`/api/admin/users/${id}`] as const;
};

export const getAdminGetUserQueryOptions = <
  TData = Awaited<ReturnType<typeof adminGetUser>>,
  TError = ErrorType<ErrorResponse>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminGetUser>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdminGetUserQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetUser>>> = ({
    signal,
  }) => adminGetUser(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof adminGetUser>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AdminGetUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminGetUser>>
>;
export type AdminGetUserQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Admin get user by ID
 */

export function useAdminGetUser<
  TData = Awaited<ReturnType<typeof adminGetUser>>,
  TError = ErrorType<ErrorResponse>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminGetUser>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAdminGetUserQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Admin update user
 */
export const getAdminUpdateUserUrl = (id: string) => {
  return `/api/admin/users/${id}`;
};

export const adminUpdateUser = async (
  id: string,
  adminUpdateUserBody: AdminUpdateUserBody,
  options?: RequestInit,
): Promise<AdminUser> => {
  return customFetch<AdminUser>(getAdminUpdateUserUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(adminUpdateUserBody),
  });
};

export const getAdminUpdateUserMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminUpdateUser>>,
    TError,
    { id: string; data: BodyType<AdminUpdateUserBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminUpdateUser>>,
  TError,
  { id: string; data: BodyType<AdminUpdateUserBody> },
  TContext
> => {
  const mutationKey = ["adminUpdateUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminUpdateUser>>,
    { id: string; data: BodyType<AdminUpdateUserBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return adminUpdateUser(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminUpdateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminUpdateUser>>
>;
export type AdminUpdateUserMutationBody = BodyType<AdminUpdateUserBody>;
export type AdminUpdateUserMutationError = ErrorType<unknown>;

/**
 * @summary Admin update user
 */
export const useAdminUpdateUser = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminUpdateUser>>,
    TError,
    { id: string; data: BodyType<AdminUpdateUserBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof adminUpdateUser>>,
  TError,
  { id: string; data: BodyType<AdminUpdateUserBody> },
  TContext
> => {
  return useMutation(getAdminUpdateUserMutationOptions(options));
};

/**
 * @summary Admin get all transactions
 */
export const getAdminGetTransactionsUrl = () => {
  return `/api/admin/transactions`;
};

export const adminGetTransactions = async (
  options?: RequestInit,
): Promise<AdminTransaction[]> => {
  return customFetch<AdminTransaction[]>(getAdminGetTransactionsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getAdminGetTransactionsQueryKey = () => {
  return [`/api/admin/transactions`] as const;
};

export const getAdminGetTransactionsQueryOptions = <
  TData = Awaited<ReturnType<typeof adminGetTransactions>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof adminGetTransactions>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdminGetTransactionsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminGetTransactions>>
  > = ({ signal }) => adminGetTransactions({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminGetTransactions>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AdminGetTransactionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminGetTransactions>>
>;
export type AdminGetTransactionsQueryError = ErrorType<unknown>;

/**
 * @summary Admin get all transactions
 */

export function useAdminGetTransactions<
  TData = Awaited<ReturnType<typeof adminGetTransactions>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof adminGetTransactions>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAdminGetTransactionsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Admin approve a transaction
 */
export const getAdminApproveTransactionUrl = (id: string) => {
  return `/api/admin/transactions/${id}/approve`;
};

export const adminApproveTransaction = async (
  id: string,
  options?: RequestInit,
): Promise<AdminTransaction> => {
  return customFetch<AdminTransaction>(getAdminApproveTransactionUrl(id), {
    ...options,
    method: "POST",
  });
};

export const getAdminApproveTransactionMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminApproveTransaction>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminApproveTransaction>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["adminApproveTransaction"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminApproveTransaction>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return adminApproveTransaction(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminApproveTransactionMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminApproveTransaction>>
>;

export type AdminApproveTransactionMutationError = ErrorType<unknown>;

/**
 * @summary Admin approve a transaction
 */
export const useAdminApproveTransaction = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminApproveTransaction>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof adminApproveTransaction>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getAdminApproveTransactionMutationOptions(options));
};

/**
 * @summary Admin reject a transaction
 */
export const getAdminRejectTransactionUrl = (id: string) => {
  return `/api/admin/transactions/${id}/reject`;
};

export const adminRejectTransaction = async (
  id: string,
  options?: RequestInit,
): Promise<AdminTransaction> => {
  return customFetch<AdminTransaction>(getAdminRejectTransactionUrl(id), {
    ...options,
    method: "POST",
  });
};

export const getAdminRejectTransactionMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminRejectTransaction>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminRejectTransaction>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["adminRejectTransaction"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminRejectTransaction>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return adminRejectTransaction(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminRejectTransactionMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminRejectTransaction>>
>;

export type AdminRejectTransactionMutationError = ErrorType<unknown>;

/**
 * @summary Admin reject a transaction
 */
export const useAdminRejectTransaction = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminRejectTransaction>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof adminRejectTransaction>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getAdminRejectTransactionMutationOptions(options));
};

/**
 * @summary Admin dashboard stats
 */
export const getAdminGetStatsUrl = () => {
  return `/api/admin/stats`;
};

export const adminGetStats = async (
  options?: RequestInit,
): Promise<AdminStats> => {
  return customFetch<AdminStats>(getAdminGetStatsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getAdminGetStatsQueryKey = () => {
  return [`/api/admin/stats`] as const;
};

export const getAdminGetStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof adminGetStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof adminGetStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdminGetStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetStats>>> = ({
    signal,
  }) => adminGetStats({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminGetStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AdminGetStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminGetStats>>
>;
export type AdminGetStatsQueryError = ErrorType<unknown>;

/**
 * @summary Admin dashboard stats
 */

export function useAdminGetStats<
  TData = Awaited<ReturnType<typeof adminGetStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof adminGetStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAdminGetStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List all conversations
 */
export const getListOpenaiConversationsUrl = () => {
  return `/api/openai/conversations`;
};

export const listOpenaiConversations = async (
  options?: RequestInit,
): Promise<OpenaiConversation[]> => {
  return customFetch<OpenaiConversation[]>(getListOpenaiConversationsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListOpenaiConversationsQueryKey = () => {
  return [`/api/openai/conversations`] as const;
};

export const getListOpenaiConversationsQueryOptions = <
  TData = Awaited<ReturnType<typeof listOpenaiConversations>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listOpenaiConversations>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListOpenaiConversationsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listOpenaiConversations>>
  > = ({ signal }) => listOpenaiConversations({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listOpenaiConversations>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListOpenaiConversationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listOpenaiConversations>>
>;
export type ListOpenaiConversationsQueryError = ErrorType<unknown>;

/**
 * @summary List all conversations
 */

export function useListOpenaiConversations<
  TData = Awaited<ReturnType<typeof listOpenaiConversations>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listOpenaiConversations>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListOpenaiConversationsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a new conversation
 */
export const getCreateOpenaiConversationUrl = () => {
  return `/api/openai/conversations`;
};

export const createOpenaiConversation = async (
  createOpenaiConversationBody: CreateOpenaiConversationBody,
  options?: RequestInit,
): Promise<OpenaiConversation> => {
  return customFetch<OpenaiConversation>(getCreateOpenaiConversationUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createOpenaiConversationBody),
  });
};

export const getCreateOpenaiConversationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOpenaiConversation>>,
    TError,
    { data: BodyType<CreateOpenaiConversationBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createOpenaiConversation>>,
  TError,
  { data: BodyType<CreateOpenaiConversationBody> },
  TContext
> => {
  const mutationKey = ["createOpenaiConversation"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createOpenaiConversation>>,
    { data: BodyType<CreateOpenaiConversationBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createOpenaiConversation(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateOpenaiConversationMutationResult = NonNullable<
  Awaited<ReturnType<typeof createOpenaiConversation>>
>;
export type CreateOpenaiConversationMutationBody =
  BodyType<CreateOpenaiConversationBody>;
export type CreateOpenaiConversationMutationError = ErrorType<unknown>;

/**
 * @summary Create a new conversation
 */
export const useCreateOpenaiConversation = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOpenaiConversation>>,
    TError,
    { data: BodyType<CreateOpenaiConversationBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createOpenaiConversation>>,
  TError,
  { data: BodyType<CreateOpenaiConversationBody> },
  TContext
> => {
  return useMutation(getCreateOpenaiConversationMutationOptions(options));
};

/**
 * @summary Get conversation with messages
 */
export const getGetOpenaiConversationUrl = (id: string) => {
  return `/api/openai/conversations/${id}`;
};

export const getOpenaiConversation = async (
  id: string,
  options?: RequestInit,
): Promise<OpenaiConversationWithMessages> => {
  return customFetch<OpenaiConversationWithMessages>(
    getGetOpenaiConversationUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetOpenaiConversationQueryKey = (id: string) => {
  return [`/api/openai/conversations/${id}`] as const;
};

export const getGetOpenaiConversationQueryOptions = <
  TData = Awaited<ReturnType<typeof getOpenaiConversation>>,
  TError = ErrorType<OpenaiError>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getOpenaiConversation>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetOpenaiConversationQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOpenaiConversation>>
  > = ({ signal }) => getOpenaiConversation(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOpenaiConversation>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetOpenaiConversationQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOpenaiConversation>>
>;
export type GetOpenaiConversationQueryError = ErrorType<OpenaiError>;

/**
 * @summary Get conversation with messages
 */

export function useGetOpenaiConversation<
  TData = Awaited<ReturnType<typeof getOpenaiConversation>>,
  TError = ErrorType<OpenaiError>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getOpenaiConversation>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetOpenaiConversationQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete a conversation
 */
export const getDeleteOpenaiConversationUrl = (id: string) => {
  return `/api/openai/conversations/${id}`;
};

export const deleteOpenaiConversation = async (
  id: string,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteOpenaiConversationUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteOpenaiConversationMutationOptions = <
  TError = ErrorType<OpenaiError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteOpenaiConversation>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteOpenaiConversation>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteOpenaiConversation"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteOpenaiConversation>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteOpenaiConversation(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteOpenaiConversationMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteOpenaiConversation>>
>;

export type DeleteOpenaiConversationMutationError = ErrorType<OpenaiError>;

/**
 * @summary Delete a conversation
 */
export const useDeleteOpenaiConversation = <
  TError = ErrorType<OpenaiError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteOpenaiConversation>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteOpenaiConversation>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteOpenaiConversationMutationOptions(options));
};

/**
 * @summary List messages in a conversation
 */
export const getListOpenaiMessagesUrl = (id: string) => {
  return `/api/openai/conversations/${id}/messages`;
};

export const listOpenaiMessages = async (
  id: string,
  options?: RequestInit,
): Promise<OpenaiMessage[]> => {
  return customFetch<OpenaiMessage[]>(getListOpenaiMessagesUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getListOpenaiMessagesQueryKey = (id: string) => {
  return [`/api/openai/conversations/${id}/messages`] as const;
};

export const getListOpenaiMessagesQueryOptions = <
  TData = Awaited<ReturnType<typeof listOpenaiMessages>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listOpenaiMessages>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListOpenaiMessagesQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listOpenaiMessages>>
  > = ({ signal }) => listOpenaiMessages(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listOpenaiMessages>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListOpenaiMessagesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listOpenaiMessages>>
>;
export type ListOpenaiMessagesQueryError = ErrorType<unknown>;

/**
 * @summary List messages in a conversation
 */

export function useListOpenaiMessages<
  TData = Awaited<ReturnType<typeof listOpenaiMessages>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listOpenaiMessages>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListOpenaiMessagesQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Send a text message and receive a streaming text response
 */
export const getSendOpenaiMessageUrl = (id: string) => {
  return `/api/openai/conversations/${id}/messages`;
};

export const sendOpenaiMessage = async (
  id: string,
  sendOpenaiMessageBody: SendOpenaiMessageBody,
  options?: RequestInit,
): Promise<unknown> => {
  return customFetch<unknown>(getSendOpenaiMessageUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(sendOpenaiMessageBody),
  });
};

export const getSendOpenaiMessageMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendOpenaiMessage>>,
    TError,
    { id: string; data: BodyType<SendOpenaiMessageBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sendOpenaiMessage>>,
  TError,
  { id: string; data: BodyType<SendOpenaiMessageBody> },
  TContext
> => {
  const mutationKey = ["sendOpenaiMessage"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sendOpenaiMessage>>,
    { id: string; data: BodyType<SendOpenaiMessageBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return sendOpenaiMessage(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SendOpenaiMessageMutationResult = NonNullable<
  Awaited<ReturnType<typeof sendOpenaiMessage>>
>;
export type SendOpenaiMessageMutationBody = BodyType<SendOpenaiMessageBody>;
export type SendOpenaiMessageMutationError = ErrorType<unknown>;

/**
 * @summary Send a text message and receive a streaming text response
 */
export const useSendOpenaiMessage = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendOpenaiMessage>>,
    TError,
    { id: string; data: BodyType<SendOpenaiMessageBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof sendOpenaiMessage>>,
  TError,
  { id: string; data: BodyType<SendOpenaiMessageBody> },
  TContext
> => {
  return useMutation(getSendOpenaiMessageMutationOptions(options));
};

/**
 * @summary Create a Stripe checkout session for buying crypto
 */
export const getCreateStripeCheckoutUrl = () => {
  return `/api/stripe/checkout`;
};

export const createStripeCheckout = async (
  createCheckoutBody: CreateCheckoutBody,
  options?: RequestInit,
): Promise<CheckoutResponse> => {
  return customFetch<CheckoutResponse>(getCreateStripeCheckoutUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createCheckoutBody),
  });
};

export const getCreateStripeCheckoutMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createStripeCheckout>>,
    TError,
    { data: BodyType<CreateCheckoutBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createStripeCheckout>>,
  TError,
  { data: BodyType<CreateCheckoutBody> },
  TContext
> => {
  const mutationKey = ["createStripeCheckout"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createStripeCheckout>>,
    { data: BodyType<CreateCheckoutBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createStripeCheckout(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateStripeCheckoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof createStripeCheckout>>
>;
export type CreateStripeCheckoutMutationBody = BodyType<CreateCheckoutBody>;
export type CreateStripeCheckoutMutationError = ErrorType<unknown>;

/**
 * @summary Create a Stripe checkout session for buying crypto
 */
export const useCreateStripeCheckout = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createStripeCheckout>>,
    TError,
    { data: BodyType<CreateCheckoutBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createStripeCheckout>>,
  TError,
  { data: BodyType<CreateCheckoutBody> },
  TContext
> => {
  return useMutation(getCreateStripeCheckoutMutationOptions(options));
};

/**
 * @summary List available crypto purchase packages
 */
export const getListStripeProductsUrl = () => {
  return `/api/stripe/products`;
};

export const listStripeProducts = async (
  options?: RequestInit,
): Promise<StripeProductsResponse> => {
  return customFetch<StripeProductsResponse>(getListStripeProductsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListStripeProductsQueryKey = () => {
  return [`/api/stripe/products`] as const;
};

export const getListStripeProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof listStripeProducts>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listStripeProducts>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListStripeProductsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listStripeProducts>>
  > = ({ signal }) => listStripeProducts({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listStripeProducts>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListStripeProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listStripeProducts>>
>;
export type ListStripeProductsQueryError = ErrorType<unknown>;

/**
 * @summary List available crypto purchase packages
 */

export function useListStripeProducts<
  TData = Awaited<ReturnType<typeof listStripeProducts>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listStripeProducts>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListStripeProductsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
